import { FC } from 'react';
import { IoMdClose } from 'react-icons/io';
import {
  Accent,
  Section,
  Subtitle,
  Text,
  TextWrap,
  Title,
  TitleWrap,
} from './StorySection.styles';
import mobileImg from '@/images/storySection/mobileBgImage.png';
import tabletImg from '@/images/storySection/tabletBgImage.png';
import desktopImg from '@/images/storySection/desktopBgImage.png';

const StorySection: FC = () => (
  <Section mobileImg={mobileImg} tabletImg={tabletImg} desktopImg={desktopImg}>
    <TitleWrap>
      <Title>
        a Story that started with <Accent>one simple ape</Accent>
      </Title>
      <Subtitle>
        WHO GOT FED UP WITH BORING AND HYPOCRITIC COMMONPLACE THIS IS HOW THE
        IDEA OF ESCAPING AND DYNAMIC JOURNEY ON THE YACHT
      </Subtitle>
    </TitleWrap>
    <TextWrap>
      <IoMdClose size={24} />
      <Text>
        EACH ARTWORK IN THE COLLECTION TELLS A STORY OF ONE JOURNEY. ARTS ARE
        RANDOMLY GENERATED BY USERS
      </Text>
    </TextWrap>
  </Section>
);

export default StorySection;
